version: "3.8"

services:
  minio:
    image: bitnami/minio:2024.3.10
    container_name: s3
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - "minio_data:/bitnami/minio/data"
      # Certificate should contain FQDN + localhost (common name + DNS)
      - "./certs:/certs"      
    environment:
      - MINIO_ROOT_USER=${S3_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${S3_ROOT_PWD}
      # public fqdn if behind reverse proxy
      - MINIO_SERVER_URL=${S3_SERVER_URL}
      # UI public fqdn if behind reverse proxy
      - MINIO_BROWSER_REDIRECT_URL=${S3_BROWSER_REDIRECT_URL}
      - MINIO_SCHEME=https
      # To enable virtual-host-style aka: my-bucket.s3.arxit.com
      - MINIO_DOMAIN=${S3_DOMAIN}
    restart: always

volumes:
  minio_data:
    driver: local
